name: Cache Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: cache-ecab781

      - name: prime-cache-ecab781
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss."
          fi
